# Generated by Django 4.0.3 on 2022-03-24 17:38

from django.db import migrations, models
import image_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=image_gallery.models.getcurrentusername),
        ),
    ]
